name: Test Docker Build

on:
  pull_request:
    branches:
      - 'paper'
      - 'fabric'
      - 'mc/*/*'

jobs:
  pr-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Paper
        uses: docker/build-push-action@v6
        with:
          push: false
          file: ./Dockerfile
